### ISSUE TITLE
Tracking changes required for full crypto backend independence

### ISSUE THREAD

**Issue by mattsb42-aws** [mpdavis/python-jose#114]
As discussed in #108 and #109, the various cryptographic backends are not all independently operable. This tracking issue will enumerate the changes that need to be made and track the PRs that fix them.

Tags will use the names for dependency grouping as defined in the extras installs, with "base" used to define the `python-rsa`/`python-ecdsa` backend.

#### cryptography

- [x] `TestECAlgorithm::test_verify` #117

#### base

- [x] `test_firebase.py::TestFirebase::test_individual_cert` #118
- [x] `test_firebase.py::TestFirebase::test_certs_dict` #118
- [x] `test_firebase.py::TestFirebase::test_certs_string` #118

#### pycrypto

passing

#### pycryptodome

passing

#### compatibility (all backends installed concurrently)

- [x] `algorithms/test_EC.py::TestECAlgorithm::test_verify` #117
- [x] `algorithms/test_RSA.py::test_cryptography_RSA_key_instance` #116

#### cryptography

`CryptographyECKey` depends on `ecdsa.utils` encoding functions.

- [x] `ecdsa.SigningKey` and `ecdsa.VerifyingKey` #117
- [x] `sigdecode_string` #117
- [x] `sigencode_string` #117
- [x] `sigdecode_der` #117
- [x] `sigencode_der` #117

#### pycrypto/dome

- [x] `pycrypto_backend.RSAKey` depends on `rsa_backend.pem_to_spki`. #121

**Comment by mattsb42-aws** [comment]
After looking into the issues with the firebase tests failing in "base" mode, my conclusion is that the root cause here is that `python-rsa` cannot load certificates. I am not familiar with Firebase, so I will assume that the tests are written in a reasonable manner and so conclude that Firebase interactions require working with certificates.

It is my conclusion, then, that if you want to use this library with Firebase or any other application that passes certificates, you will need one of the more fully featured crypto backends.

**Comment by mpdavis** [comment]
@mattsb42-aws I want to thank you for all of this effort, especially over Christmas. I'm looking at this now to hopefully get all of these merged.

**Comment by mattsb42-aws** [comment]
Happy to help!

While I had my head in this space I went ahead and tackled the `pycrypto/dome` dependency on `python-rsa` too by centralizing the ASN1 handling into a separate module. This change fully removes any dependency on `python-rsa` or `python-ecdsa` outside of those specific backend modules (albeit by making `pyasn1` a dependency of the `pycrypto/dome` backends).

I'm going to hold off on cutting that PR until #120 is merged, just because it builds very heavily on top of the changes in that.

I still haven't found a solution to the problem of how to have "default" extras; not sure what a good approach to that will be.

**Comment by mattsb42-aws** [comment]
#121 and #122 should wrap this up and clear the way for merging the backend isolation dev branch in.

**Comment by mattsb42-aws** [comment]
We're on the final stretch! #128 is prepping `backend-explicit-tests` for merge into `master` by doing the reverse (the changes to `master` since `backend-explicit-tests` forked off are much less than the changes that `backend-explicit-tests` introduces).

**Comment by mattsb42-aws** [comment]
This is resolved with #129
